pipeline {
    agent any

    stages {
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Lint/Format') {
            steps {
                sh 'npx eslint . || echo "ESLint not set up, skipping..."'
            }
        }

        stage('Run App') {
            steps {
                echo "App start"
            }
        }
    }
}
