pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test || echo "No tests yet"'
            }
        }

        stage('Static Code Analysis') {
            steps {
                sh 'sonar-scanner'
            }
        }
    }
}
